export interface accountmaintain {
    id?;
    name?;
    userid?;
    password?;
    disabled?;
    activeStartDate?;
    activeEndDate?;
    email?;
    groupid?;
    groupname?;
    isDefault?;
    roleid?;
    rname?;
    dname?;
    issucessful?;
    loginip?;
    logindate?;
}